language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sushilkadu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sushilkadu/react-test npm test

after_success:
  - docker build -t sushilkadu/multi-client ./client
  - docker build -t sushilkadu/multi-nginx ./nginx
  - docker build -t sushilkadu/multi-server ./server
  - docker build -t sushilkadu/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sushilkadu/multi-client
  - docker push sushilkadu/multi-nginx
  - docker push sushilkadu/multi-server
  - docker push sushilkadu/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-south-1
  app: Multi-Docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-073731903074
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
